new logsheet created logsheet {
    dataValues: {
        id: 780,
        survey_type: 'CAMPAIGN',
        logsheet_date: 2017 - 07 - 10 T02: 32: 37.708 Z,
        julian_day: 191,
        location: 'asd',
        marker: 'asd',
        siteId: 1,
        north: 1,
        east: 2,
        south: 5,
        west: 3,
        time_start: '2017-07-10T02:32:47.251Z',
        azimuth: 4,
        avg_slant_height: 2.75,
        antennaId: '123456789',
        receiverId: '123456789',
        contactPersonId: null,
        updatedAt: 2017 - 07 - 10 T02: 32: 49.654 Z,
        createdAt: 2017 - 07 - 10 T02: 32: 49.654 Z
    },
    _previousDataValues: {
        survey_type: 'CAMPAIGN',
        logsheet_date: 2017 - 07 - 10 T02: 32: 37.708 Z,
        julian_day: 191,
        location: 'asd',
        marker: 'asd',
        siteId: 1,
        north: 1,
        east: 2,
        south: 5,
        west: 3,
        time_start: '2017-07-10T02:32:47.251Z',
        azimuth: 4,
        avg_slant_height: 2.75,
        antennaId: '123456789',
        receiverId: '123456789',
        contactPersonId: null,
        id: 780,
        time_end: undefined,
        failure_time: undefined,
        receiver_status: undefined,
        antenna_status: undefined,
        rod_num: undefined,
        rod_correction: undefined,
        ip_add: undefined,
        netmask: undefined,
        gateway: undefined,
        dns: undefined,
        local_tcp_port: undefined,
        latitude: undefined,
        longitude: undefined,
        observed_situation: undefined,
        lodging_road_information: undefined,
        others: undefined,
        createdAt: 2017 - 07 - 10 T02: 32: 49.654 Z,
        updatedAt: 2017 - 07 - 10 T02: 32: 49.654 Z,
        fieldworkId: undefined
    },
    _changed: {
        survey_type: false,
        logsheet_date: false,
        julian_day: false,
        location: false,
        marker: false,
        siteId: false,
        north: false,
        east: false,
        south: false,
        west: false,
        time_start: false,
        azimuth: false,
        avg_slant_height: false,
        antennaId: false,
        receiverId: false,
        contactPersonId: false,
        id: false,
        time_end: false,
        failure_time: false,
        receiver_status: false,
        antenna_status: false,
        rod_num: false,
        rod_correction: false,
        ip_add: false,
        netmask: false,
        gateway: false,
        dns: false,
        local_tcp_port: false,
        latitude: false,
        longitude: false,
        observed_situation: false,
        lodging_road_information: false,
        others: false,
        createdAt: false,
        updatedAt: false,
        fieldworkId: false
    },
    _modelOptions: {
        timestamps: true,
        validate: {},
        freezeTableName: false,
        underscored: false,
        underscoredAll: false,
        paranoid: false,
        rejectOnEmpty: false,
        whereCollection: {
            siteId: 427
        },
        schema: null,
        schemaDelimiter: '',
        defaultScope: {},
        scopes: [],
        hooks: {},
        indexes: [],
        name: {
            plural: 'logsheets',
            singular: 'logsheet'
        },
        omitNull: false,
        sequelize: Sequelize {
            options: [Object],
            config: [Object],
            dialect: [Object],
            models: [Object],
            modelManager: [Object],
            connectionManager: [Object],
            importCache: {},
            test: [Object],
            queryInterface: [Object]
        },
        uniqueKeys: {},
        hasPrimaryKeys: true
    },
    _options: {
        isNewRecord: true,
        _schema: null,
        _schemaDelimiter: '',
        attributes: undefined,
        include: undefined,
        raw: undefined,
        silent: undefined
    },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false
}